<a href="https://colab.research.google.com/github/AlexBugalter/Lesson/blob/main/NumPy/NumPy_where_%D0%A3%D1%81%D0%BB%D0%BE%D0%B2%D0%BD%D0%B0%D1%8F_%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0_%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2_%D0%BC%D0%B0%D1%81%D1%81%D0%B8%D0%B2%D0%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Использование np.where() для замены элементов в массиве NumPy

Этот код заменяет элементы в массиве arr на 'Met', если они больше 5, и на 'Not Met' в противном случае, и сохраняет результат в переменной replaced.

In [1]:
# Использование np.where() для замены элементов в массиве
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
replaced = np.where(arr > 5, 'Met', 'Not Met')
print(replaced)

['Not Met' 'Not Met' 'Not Met' 'Not Met' 'Not Met' 'Met' 'Met' 'Met' 'Met'
 'Met']


Аналогично, мы можем использовать массивы в качестве наших выборок. Например, если вы хотите вернуть исходный массив, если условие выполнено, или другое значение, вы можете написать следующее:

In [2]:
# Использование np.where() для замены элементов в массиве другими значениями из массива
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
replaced = np.where(arr > 5, arr, -1)
print(replaced)

[-1 -1 -1 -1 -1  6  7  8  9 10]


## Использование np.where() для обработки элементов массива NumPy

Этот код умножает на 10 элементы массива arr, которые четные, и делит на 10 элементы, которые нечетные, и сохраняет результат в переменной replaced.

In [4]:
# Использование np.where() для обработки элементов в массиве
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
replaced = np.where(arr % 2 == 0, arr * 10, arr / 10)
print(replaced)

[  0.1  20.    0.3  40.    0.5  60.    0.7  80.    0.9 100. ]


Допустим, у нас есть список значений, которые идентифицируют объект как квадрат или круг. У нас также есть массив, который содержит либо радиус круга, либо длину стороны квадрата. Мы можем использовать функцию np.where() для возврата массива площадей, как показано ниже:

In [3]:
types = ['square', 'circle', 'square', 'circle', 'circle', 'square']
arr = np.array([2.3, 3.4, 1.2, 5.4, 3.2, 1.1])
areas = np.where(types == 'square', arr ** 2, np.pi * arr ** 2)
print(areas)

[16.61902514 36.31681108  4.52389342 91.60884178 32.16990877  3.80132711]


Этот код вычисляет площадь для каждой фигуры в массиве arr, где тип фигуры равен 'square', используя формулу сторона ** 2, а для фигур типа 'circle', используется формула pi * радиус ** 2, и сохраняет результат в переменной areas.

## Использование np.where() с несколькими условиями

Этот код создает новый массив filtered, в котором значения из массива arr сохраняются, если они четные и больше 5, иначе они заменяются на 0.

In [5]:
arr = np.arange(10)

filtered = np.where((arr % 2 == 0) & (arr > 5), arr, 0)
print(filtered)

[0 0 0 0 0 0 6 0 8 0]


Мы также можем выбирать элементы, если выполнено хотя бы одно из условий, используя оператор |. Давайте посмотрим, как это выглядит:

In [6]:
arr = np.arange(10)

filtered = np.where((arr % 2 == 0) | (arr > 5), arr, 0)
print(filtered)

[0 0 2 0 4 0 6 7 8 9]


## Использование np.where() с несколькими измерениями

Этот код создает новую матрицу, где значения из исходной матрицы arr сохраняются, если они четные, иначе они заменяются на -1.

In [7]:
arr = np.arange(9).reshape(3, 3)

filtered = np.where(arr % 2 == 0, arr, -1)
print(filtered)

[[ 0 -1  2]
 [-1  4 -1]
 [ 6 -1  8]]


## Использование np.where() для возврата индексов, в которых выполняется условие

Этот код возвращает индексы элементов массива arr, для которых условие остатка от деления на 2 равно 0.

In [8]:
arr = np.arange(9)

idx = np.where(arr % 2 == 0)
print(idx)

(array([0, 2, 4, 6, 8]),)
